create table if not exists public.songs (
  id bigint generated by default as identity primary key,
  title text not null,
  artist text not null,
  normalized_title text not null,
  normalized_artist text not null,
  file_id text not null unique,
  source_url text,
  play_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists songs_artist_idx on public.songs (normalized_artist);
create index if not exists songs_plays_idx on public.songs (play_count desc);

create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  file_id text not null,
  title text not null,
  artist text not null,
  created_at timestamptz not null default now(),
  unique (user_id, file_id)
);

create index if not exists favorites_user_idx on public.favorites (user_id, created_at desc);

-- Users: used for /admin statistics, blocking (ban) and auto-detecting who blocked the bot.
create table if not exists public.users (
  user_id bigint primary key,
  username text,
  first_name text,
  last_name text,
  is_admin boolean not null default false,
  is_banned boolean not null default false,
  banned_reason text,
  banned_at timestamptz,
  started_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  blocked_at timestamptz
);

create index if not exists users_seen_idx on public.users (last_seen_at desc);
create index if not exists users_blocked_idx on public.users (blocked_at) where blocked_at is not null;

-- Mandatory subscription channels configured from the admin panel.
create table if not exists public.required_channels (
  id bigint generated by default as identity primary key,
  chat_id bigint not null unique,
  username text,
  title text,
  created_at timestamptz not null default now()
);
