create table if not exists public.songs (
  id bigint generated by default as identity primary key,
  title text not null,
  artist text not null,
  normalized_title text not null,
  normalized_artist text not null,
  file_id text not null unique,
  source_url text,
  play_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists songs_artist_idx on public.songs (normalized_artist);
create index if not exists songs_plays_idx on public.songs (play_count desc);