from .spotify import SpotifyTrack

# Offline fallback for «Топ 100» when SPOTIFY_CLIENT_ID/SECRET are not set.
# Kept at exactly 100 tracks so the chart is complete without Spotify access;
# it is shown 10 tracks per page with ⏪ / ⏩ buttons.
TOP_100_FALLBACK = [
    SpotifyTrack("Espresso", "Sabrina Carpenter"),
    SpotifyTrack("BIRDS OF A FEATHER", "Billie Eilish"),
    SpotifyTrack("Good Luck Babe", "Chappell Roan"),
    SpotifyTrack("Not Like Us", "Kendrick Lamar"),
    SpotifyTrack("Sunflower", "Post Malone"),
    SpotifyTrack("Blinding Lights", "The Weeknd"),
    SpotifyTrack("As It Was", "Harry Styles"),
    SpotifyTrack("Flowers", "Miley Cyrus"),
    SpotifyTrack("Kill Bill", "SZA"),
    SpotifyTrack("Levitating", "Dua Lipa"),
    SpotifyTrack("Anti-Hero", "Taylor Swift"),
    SpotifyTrack("Tití Me Preguntó", "Bad Bunny"),
    SpotifyTrack("Rich Flex", "Drake"),
    SpotifyTrack("Last Night", "Morgan Wallen"),
    SpotifyTrack("Ella Baila Sola", "Peso Pluma"),
    SpotifyTrack("Seven", "Jung Kook"),
    SpotifyTrack("Summertime Sadness", "Lana Del Rey"),
    SpotifyTrack("R U Mine?", "Arctic Monkeys"),
    SpotifyTrack("Santé", "Stromae"),
    SpotifyTrack("Titanium", "David Guetta"),
    SpotifyTrack("Cruel Summer", "Taylor Swift"),
    SpotifyTrack("Vampire", "Olivia Rodrigo"),
    SpotifyTrack("Paint The Town Red", "Doja Cat"),
    SpotifyTrack("Snooze", "SZA"),
    SpotifyTrack("Fast Car", "Luke Combs"),
    SpotifyTrack("Fukumean", "Gunna"),
    SpotifyTrack("I Remember Everything", "Zach Bryan"),
    SpotifyTrack("Dance The Night", "Dua Lipa"),
    SpotifyTrack("Water", "Tyla"),
    SpotifyTrack("Greedy", "Tate McRae"),
    SpotifyTrack("Strangers", "Kenya Grace"),
    SpotifyTrack("Lovin On Me", "Jack Harlow"),
    SpotifyTrack("Used To Be Young", "Miley Cyrus"),
    SpotifyTrack("FE!N", "Travis Scott"),
    SpotifyTrack("K-POP", "Travis Scott"),
    SpotifyTrack("Daylight", "David Kushner"),
    SpotifyTrack("Calm Down", "Rema"),
    SpotifyTrack("La Bebe", "Yng Lvcas"),
    SpotifyTrack("Unholy", "Sam Smith"),
    SpotifyTrack("Creepin'", "Metro Boomin"),
    SpotifyTrack("Boy's a liar Pt. 2", "PinkPantheress"),
    SpotifyTrack("Flowers (Demo)", "Miley Cyrus"),
    SpotifyTrack("Die For You", "The Weeknd"),
    SpotifyTrack("Sure Thing", "Miguel"),
    SpotifyTrack("Under The Influence", "Chris Brown"),
    SpotifyTrack("Made You Look", "Meghan Trainor"),
    SpotifyTrack("About Damn Time", "Lizzo"),
    SpotifyTrack("Late Night Talking", "Harry Styles"),
    SpotifyTrack("Sunroof", "Nicky Youre"),
    SpotifyTrack("Heat Waves", "Glass Animals"),
    SpotifyTrack("Stay", "The Kid LAROI"),
    SpotifyTrack("Bad Habits", "Ed Sheeran"),
    SpotifyTrack("Save Your Tears", "The Weeknd"),
    SpotifyTrack("Peaches", "Justin Bieber"),
    SpotifyTrack("Montero", "Lil Nas X"),
    SpotifyTrack("Drivers License", "Olivia Rodrigo"),
    SpotifyTrack("Positions", "Ariana Grande"),
    SpotifyTrack("Mood", "24kGoldn"),
    SpotifyTrack("Watermelon Sugar", "Harry Styles"),
    SpotifyTrack("Rain On Me", "Lady Gaga"),
    SpotifyTrack("Don't Start Now", "Dua Lipa"),
    SpotifyTrack("Someone You Loved", "Lewis Capaldi"),
    SpotifyTrack("Circles", "Post Malone"),
    SpotifyTrack("Señorita", "Shawn Mendes"),
    SpotifyTrack("bad guy", "Billie Eilish"),
    SpotifyTrack("Old Town Road", "Lil Nas X"),
    SpotifyTrack("Sunflower (Live)", "Post Malone"),
    SpotifyTrack("Shape of You", "Ed Sheeran"),
    SpotifyTrack("Despacito", "Luis Fonsi"),
    SpotifyTrack("Something Just Like This", "The Chainsmokers"),
    SpotifyTrack("Closer", "The Chainsmokers"),
    SpotifyTrack("One Dance", "Drake"),
    SpotifyTrack("Sorry", "Justin Bieber"),
    SpotifyTrack("Love Yourself", "Justin Bieber"),
    SpotifyTrack("Hello", "Adele"),
    SpotifyTrack("Uptown Funk", "Mark Ronson"),
    SpotifyTrack("Thinking Out Loud", "Ed Sheeran"),
    SpotifyTrack("Shake It Off", "Taylor Swift"),
    SpotifyTrack("All About That Bass", "Meghan Trainor"),
    SpotifyTrack("Happy", "Pharrell Williams"),
    SpotifyTrack("Roar", "Katy Perry"),
    SpotifyTrack("Get Lucky", "Daft Punk"),
    SpotifyTrack("Locked Out of Heaven", "Bruno Mars"),
    SpotifyTrack("Diamonds", "Rihanna"),
    SpotifyTrack("Somebody That I Used To Know", "Gotye"),
    SpotifyTrack("Call Me Maybe", "Carly Rae Jepsen"),
    SpotifyTrack("Rolling in the Deep", "Adele"),
    SpotifyTrack("Firework", "Katy Perry"),
    SpotifyTrack("Just the Way You Are", "Bruno Mars"),
    SpotifyTrack("Love The Way You Lie", "Eminem"),
    SpotifyTrack("Bad Romance", "Lady Gaga"),
    SpotifyTrack("I Gotta Feeling", "Black Eyed Peas"),
    SpotifyTrack("Poker Face", "Lady Gaga"),
    SpotifyTrack("Viva La Vida", "Coldplay"),
    SpotifyTrack("Umbrella", "Rihanna"),
    SpotifyTrack("Beautiful Girls", "Sean Kingston"),
    SpotifyTrack("Hey There Delilah", "Plain White T's"),
    SpotifyTrack("Irreplaceable", "Beyoncé"),
    SpotifyTrack("SexyBack", "Justin Timberlake"),
    SpotifyTrack("Hips Don't Lie", "Shakira"),
    SpotifyTrack("You're Beautiful", "James Blunt"),
]
